export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
//This is the main layout of your application. 
// You can use it to add UI elements that are shared across all pages (e.g. navigation, footer, etc).
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
